server:
  port: 5656
  error:
    path: ./logs/error

eureka:
  client:
    register-with-eureka:true
    fetch-registry:true
   service-url:
     defaultZone: http://localhost:5656/eureka
   instance:
     hostname:localhost
